# phpo · Nginx 1.25
user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 100m;
    server_tokens off;
    gzip on;
    include /etc/nginx/conf.d/*.conf;
    # phpo vhosts 目录（挂载自主机的 NGINX_SITES_ROOT）
    include /etc/nginx/sites/*.conf;
}